import imageone from "/featured-image-1.png";
import imagetwo from "/featured-image-2.png";
import imagethree from "/featured-image-3.png";
import imagetfour from "/featured-image-4.png";

export const featuredListingsData = [
  {
    id: 1,
    image: imageone,
    price: 2800,
    title: "Ataz Standard House",
    location: "Pluto Street, Indonesia",
  },
  {
    id: 2,
    image: imagetwo,
    price: 4800,
    title: "Qiri Minimalist House",
    location: "Jupiter Street, Indonesia",
  },
  {
    id: 3,
    image: imagethree,
    price: 6800,
    title: "Qanan Luxury House",
    location: "Michigan Street, USA",
  },
  {
    id: 4,
    image: imagetfour,
    price: 8800,
    title: "Tingah Elegant House",
    location: "Halsted Street, USA",
  },
];

export const listingsPageData = [
  {
    id: 1,
    image: imageone,
    price: 2800,
    title: "Ataz Standard House",
    location: "Pluto Street, Indonesia",
    sqft: 800,
    bedrooms: 1,
    badrooms: 2,
  },
  {
    id: 2,
    image: imagetwo,
    price: 4800,
    title: "Qiri Minimalist House",
    location: "Jupiter Street, Indonesia",
    sqft: 1800,
    bedrooms: 2,
    badrooms: 3,
  },
  {
    id: 3,
    image: imagethree,
    price: 6800,
    title: "Qanan Luxury House",
    location: "Michigan Street, USA",
    sqft: 2800,
    bedrooms: 3,
    badrooms: 4,
  },
  {
    id: 4,
    image: imagetfour,
    price: 8800,
    title: "Tingah Elegant House",
    location: "Halsted Street, USA",
    sqft: 3800,
    bedrooms: 4,
    badrooms: 5,
  },
  {
    id: 5,
    image: imageone,
    price: 2800,
    title: "Ataz Standard House",
    location: "Pluto Street, Indonesia",
    sqft: 800,
    bedrooms: 1,
    badrooms: 2,
  },
  {
    id: 6,
    image: imagetwo,
    price: 4800,
    title: "Qiri Minimalist House",
    location: "Jupiter Street, Indonesia",
    sqft: 1800,
    bedrooms: 2,
    badrooms: 3,
  },
  {
    id: 7,
    image: imagethree,
    price: 6800,
    title: "Qanan Luxury House",
    location: "Michigan Street, USA",
    sqft: 2800,
    bedrooms: 3,
    badrooms: 4,
  },
  {
    id: 8,
    image: imagetfour,
    price: 8800,
    title: "Tingah Elegant House",
    location: "Halsted Street, USA",
    sqft: 3800,
    bedrooms: 4,
    badrooms: 5,
  },
  {
    id: 9,
    image: imageone,
    price: 2800,
    title: "Ataz Standard House",
    location: "Pluto Street, Indonesia",
    sqft: 800,
    bedrooms: 1,
    badrooms: 2,
  },
  {
    id: 10,
    image: imagetwo,
    price: 4800,
    title: "Qiri Minimalist House",
    location: "Jupiter Street, Indonesia",
    sqft: 1800,
    bedrooms: 2,
    badrooms: 3,
  },
  {
    id: 11,
    image: imagethree,
    price: 6800,
    title: "Qanan Luxury House",
    location: "Michigan Street, USA",
    sqft: 2800,
    bedrooms: 3,
    badrooms: 4,
  },
  {
    id: 12,
    image: imagetfour,
    price: 8800,
    title: "Tingah Elegant House",
    location: "Halsted Street, USA",
    sqft: 3800,
    bedrooms: 4,
    badrooms: 5,
  },
];
